### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by jordi-petit** [brenopolanski/remark-boilerplate#1]
Hello! Whenever I tried to follow the steps in the README.md file in order to deploy my slides to github pages, the only thing I get is my README shown. What could I be missing?

**Comment by cvakiitho** [comment]
Hi, please post how the deploy is failing.

**Comment by brenopolanski** [comment]
hey @jordi-petit 

Maybe you should to go on `Settings` on your repository:

![screenshot from 2019-02-20 17-56-45](https://user-images.githubusercontent.com/1894191/53124011-2021ba00-3539-11e9-8473-6b40e954ce4f.png)

and choose the correct branch for the **slides**:

![screenshot from 2019-02-20 17-56-56](https://user-images.githubusercontent.com/1894191/53124083-47788700-3539-11e9-987d-ea7db2d32ccb.png)

Try it :point_up_2:
